bdclinica/bdclinica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

bdclinica/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index_alias'),
    path('proc_menu', views.procedimento_menu.as_view(), name='proc_menu_alias'),
    path('procedimento_list/', views.procedimento_list.as_view(), name='procedimento_list_alias'),
    path('procedimento_create/', views.procedimento_create.as_view(), name='procedimento_create_alias'),
    path('procedimento_update/<int:pk>/', views.procedimento_update.as_view(), name='procedimento_update_alias'),
    path('procedimento_delete/<int:pk>/', views.procedimento_delete.as_view(), name='procedimento_delete_alias'),
    path('users_menu', views.UserListView.as_view(), name='user_menu_alias'),
    path('users_create/', views.UserCreateView2.as_view(), name='user_create_alias'),
    path('users_update/<int:pk>', views.UserUpdateView.as_view(), name='user_update_alias'),
    path('users_delete/<int:pk>', views.UserDeleteView.as_view(), name='user_delete_alias'),
    path('alterar_senha/<int:pk>',views.ChangePasswordUser.as_view(), name='alterar_senha_alias'),
]

bdclinica/myapp/models.py
from django.db import models
from django.contrib.auth.models import User,Group
import django_tables2 as tables
from django.urls import reverse
from django_tables2.utils import A
from django.utils.html import format_html

class Paciente(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="Paciente")
    data_nascimento = models.DateField(blank=True, null=True, verbose_name="Data de Nascimento")

    def clean(self):
        if self.data_nascimento and self.data_nascimento > date.today():
            raise ValidationError("A data de nascimento não pode ser no futuro.")

    def __str__(self):
        return self.usuario.get_full_name() or self.usuario.username
    
    @property
    def primeiro_nome(self):
        return self.usuario.first_name
    
    @property
    def ultimo_nome(self):
        return self.usuario.last_name

    @property
    def email(self):
        return self.usuario.email
    
    @property
    def data_cadastro(self):
        return self.usuario.date_joined

class Medico(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="Medico")
    data_nascimento = models.DateField(blank=True, null=True, verbose_name="Data de Nascimento")

    def clean(self):
        if self.data_nascimento and self.data_nascimento > date.today():
            raise ValidationError("A data de nascimento não pode ser no futuro.")

    def __str__(self):
        return self.usuario.get_full_name() or self.usuario.username
    
    @property
    def primeiro_nome(self):
        return self.usuario.first_name
    
    @property
    def ultimo_nome(self):
        return self.usuario.last_name

    @property
    def email(self):
        return self.usuario.email
    
    @property
    def data_cadastro(self):
        return self.usuario.date_joined

class Funcionario(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="Funcionario")
    data_nascimento = models.DateField(blank=True, null=True, verbose_name="Data de Nascimento")

    def clean(self):
        if self.data_nascimento and self.data_nascimento > date.today():
            raise ValidationError("A data de nascimento não pode ser no futuro.")

    def __str__(self):
        return self.usuario.get_full_name() or self.usuario.username
    
    @property
    def primeiro_nome(self):
        return self.usuario.first_name
    
    @property
    def ultimo_nome(self):
        return self.usuario.last_name

    @property
    def email(self):
        return self.usuario.email
    
    @property
    def data_cadastro(self):
        return self.usuario.date_joined
    
class Procedimento(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False, verbose_name="Nome")
    paciente = models.ForeignKey(
        Paciente, on_delete=models.CASCADE, verbose_name="paciente"
    )
    medico = models.ForeignKey(
        Medico, on_delete=models.SET_NULL, null=True, verbose_name="medico"
    )
    data = models.DateField()
    data_cadastro = models.DateTimeField(auto_now_add=True) 
    descricao = models.TextField()

    def __str__(self):
        return self.nome
    
    class Meta:
        ordering = ['nome','data']

            

bdclinica/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseForbidden
from django.contrib.auth import authenticate, login, logout
from .models import Procedimento
from django.views.generic import CreateView, ListView, UpdateView, DeleteView,FormView
from django.urls import reverse_lazy
from django_tables2 import SingleTableView
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm,SetPasswordForm
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.mixins import UserPassesTestMixin


# Mixin para verificar se o usuário é funcionário ou administrador
class AdminOrFuncionarioRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.groups.filter(name='Funcionario').exists()

    def handle_no_permission(self):
        return HttpResponseForbidden("Apenas administradores ou funcionários podem acessar esta página.")

class AdminOrFuncionarioOrMedicoRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.groups.filter(name__in=['Funcionario','Medico']).exists()

    def handle_no_permission(self):
        return HttpResponseForbidden("Apenas administradores , Medicos ou funcionários podem acessar esta página.")

def index(request):
    usuario = request.POST.get('username')
    senha = request.POST.get('password')
    user = authenticate(username=usuario, password=senha)
    if user is not None:
        login(request, user)
        request.session['username'] = usuario
        request.session['password'] = senha
        request.session['usernamefull'] = user.get_full_name()

        # Redireciona para o Django Admin se o usuário for um superusuário
        if user.is_superuser:
            return redirect('/admin/')

        if request.user.groups.filter(name='Medico').exists():
            return redirect('proc_menu_alias')
        elif request.user.groups.filter(name='Funcionario').exists():
            return render(request, 'myapp/func_menu.html')
        elif request.user.groups.filter(name='Paciente').exists():
            return redirect('procedimento_list_alias')
        else:
            return HttpResponseForbidden("Usuário sem Função")

    else:
        return render(request, 'index.html')

# Listagem de procedimentos
class procedimento_list(SingleTableView):
    from .tables import procedimento_table
    model = Procedimento
    table_class = procedimento_table
    template_name = 'myapp/procedimento_list.html'


# Criação de procedimentos (restrito a funcionários e administradores)
class procedimento_create(AdminOrFuncionarioOrMedicoRequiredMixin, CreateView):
    model = Procedimento
    fields = ['nome', 'paciente', 'medico', 'data', 'descricao']

    def get_success_url(self):
        return reverse_lazy('proc_menu_alias')


# Atualização de procedimentos (restrito a funcionários e administradores)
class procedimento_update(AdminOrFuncionarioOrMedicoRequiredMixin, UpdateView):
    model = Procedimento
    fields = ['nome', 'paciente', 'medico', 'data', 'descricao']

    def get_success_url(self):
        return reverse_lazy('proc_menu_alias')


# Exclusão de procedimentos (restrito a funcionários e administradores)
class procedimento_delete(AdminOrFuncionarioOrMedicoRequiredMixin, DeleteView):
    model = Procedimento
    #template_name_suffix = '_delete'
    template_name = 'myapp/procedimento_delete.html'
    def get_success_url(self):
        return reverse_lazy('proc_menu_alias')


# Menu de procedimentos
class procedimento_menu(SingleTableView):
    from .tables import procedimento_table
    model = Procedimento
    table_class = procedimento_table
    template_name_suffix = '_menu'
    table_pagination = {"per_page": 10}
    template_name = 'myapp/proc_menu.html'




    # Listagem dos usuários
class UserListView( SingleTableView):
    from .tables import UserTable
    model = User
    table_class = UserTable
    template_name = 'myapp/user_menu.html'
    def get_queryset(self):
        return User.objects.prefetch_related("groups")
    
    def get_table(self, *args, **kwargs):
        table = super().get_table(*args, **kwargs)
        for record in table.data:
            # Forçando a chamada do método render_cargo
            record.cargo = table.render_cargo(record)
        return table 
    
### Criacao dos usuários
class UserCreateView(AdminOrFuncionarioRequiredMixin, CreateView):
    model = User
    form_class = UserCreationForm
    form = UserChangeForm
    add_form = UserCreationForm
    template_name = "myapp/user_form.html"
    def get_success_url(self):
        return reverse_lazy('user_menu_alias')


class UserCreateView2(AdminOrFuncionarioRequiredMixin, CreateView):
    model = User
    fields = ['username', 'first_name', 'last_name', 'email']
    template_name="myapp/user_form2.html"
    def get_success_url(self):
        return reverse_lazy('user_menu_alias')

    
# Edição de usuários
class UserUpdateView(AdminOrFuncionarioRequiredMixin, UpdateView):    
    model = User
    fields = ['username', 'first_name', 'last_name', 'email']
    template_name = 'myapp/user_form2.html'
    def get_success_url(self):
        return reverse_lazy('user_menu_alias')   

# Exclusão de usuários
class UserDeleteView(AdminOrFuncionarioRequiredMixin, DeleteView):
    model = User
    template_name = 'myapp/user_delete.html'
    def get_success_url(self):
        return reverse_lazy('user_menu_alias')

class ChangePasswordUser_old(AdminOrFuncionarioRequiredMixin,FormView):
    template_name='myapp/alterar_senha.html'
    form=SetPasswordForm
    fields = ['new_password1','new_password2']
    def get_success_url(self):
        return reverse_lazy('user_menu_alias')

class ChangePasswordUser(FormView):
    template_name = 'myapp/alterar_senha.html'
    form_class = SetPasswordForm  # <-- O correto é `form_class`
    def get_user(self):
        try:
            return User.objects.get(pk=self.kwargs['pk'])
        except:
            return None 
        
    def get_form(self, form_class=None):
        """ Garante que o formulário seja instanciado com o usuário correto. """
        user = self.get_user()
        return self.form_class(user=user, **self.get_form_kwargs())

    def form_valid(self, form):
        """ Salva a nova senha e redireciona. """
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('user_menu_alias')

bdclinica/myapp/templates/myapp/alterar_senha.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}

{% block title %}Alterar Senha{% endblock %}

{% block content %}
<div class="container">
    <div class="custom-card">
        <div class="custom-header text-center">
            <h1>Alterar Senha</h1>
        </div>
        <div class="custom-body text-center">
            <div class="image-container">
                <img src="{% static 'users.png' %}" class="img-fluid my-4" alt="Usuário" width="200px">
            </div>
        
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <div class="row"> 
                    <center>
                    <div class="col-md-6 mb-3">
                        
                        {% bootstrap_field form.new_password1 placeholder='Senha' %}
                    
                    </div>
                </center> 
                </div>

            
                    <div class="row">
                        <center>
                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.new_password2 placeholder='Confirme a Senha' %}
                    </div>
                         </center>
                </div>
       
                <div class="row mt-4">
                    <div class="col-md-6">
                        <a href="{% url 'user_menu_alias' %}" class="btn btn-secondary btn-block">Voltar</a>
                    </div>
                    <div class="col-md-6 text-end">
                        <button type="submit" class="btn btn-primary btn-block">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

bdclinica/myapp/templates/myapp/func_menu.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}

{% block title %}Menu Principal - Funcionário{% endblock %}

{% block content %}
<div class="container">'
    <center>
    <div class="custom-card">
        <div class="custom-header">
            <h1>Menu Principal - Funcionário</h1>
        </div>
        <div class="custom-body">
            <div class="image-container">
                <img src="{% static 'recrutamento.png' %}" class="img-fluid" alt="Menu Principal" width="200px">
            </div>
            
            <!-- Menu de Ações -->
            <div class="row justify-content-center mt-4">
                <div class="col-md-6 mb-3">
                    <a href="{% url 'user_menu_alias' %}" class="list-group-item list-group-item-action menu-item">
                        Gerenciar Usuários
                    </a>
                </div>
                <div class="col-md-6 mb-3">
                    <a href="{% url 'proc_menu_alias' %}" class="list-group-item list-group-item-action menu-item">
                        Gerenciar Procedimentos
                    </a>
                </div>
            </div>
            
            <div class="button-group">
                <a href="{% url 'index_alias' %}" class="btn btn-danger text-white">
                    Sair
                </a>
            </div>
        </div>
    </div>
    </center>
</div>
{% endblock %}

bdclinica/myapp/templates/myapp/proc_menu.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}
{% load render_table from django_tables2 %}


{% block title %}Gerenciar Procedimentos{% endblock %}

{% block content %}
<div class="container">
    <div class="custom-card">
        <Center>
        <div class="custom-header">
            <h1>Gerenciar Procedimentos</h1>
        </div>
        </Center>
        <div class="custom-body">
            <Center>
            <div class="image-container">
                <img src="{% static 'procedimentos.png' %}" alt="Menu" width="200px">
            </div>
            </Center>
            <div class="table-responsive">
                {% render_table table %}
            </div>
            <div class="button-group">
                <a href="{% url 'procedimento_create_alias' %}" class="btn btn-success">
                    <i class="bi bi-person-plus"></i> Incluir Novo Procedimento
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bdclinica/myapp/templates/myapp/procedimento_delete.html
{% extends "base.html" %}

{% block title %}Excluir Procedimento{% endblock %}

{% block content %}
<div class="container">
    <div class="card mt-5">
        <div class="card-header">
            <h1>Tem certeza que deseja excluir este procedimento?</h1>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <button type="submit" class="btn btn-danger">Excluir</button>
                    <a href="{% url 'procedimento_list_alias' %}" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

bdclinica/myapp/templates/myapp/procedimento_form.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}

{% block title %}{% if form.instance.pk %}Editar Procedimento{% else %}Incluir Procedimento{% endif %}{% endblock %}

{% block content %}
<div class="container">
    <div class="custom-card">
    <center>
        <div class="custom-header">
            <h1>{% if form.instance.pk %}Editar Procedimento{% else %}Incluir Procedimento{% endif %}</h1>
        </div>
    </center>
        <div class="custom-body">
        <center>
            <div class="image-container">
                <img src="{% static 'procedimentos.png' %}" alt="Procedimento" width="200px">
            </div>
        </center>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <div class="row">
                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.nome placeholder='Nome do Procedimento' %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.paciente placeholder='Paciente' %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.medico placeholder='Médico' %}
                    </div>
                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.data placeholder='Data' %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.descricao placeholder='Descrição do Procedimento' %}
                    </div>
                </div>

                <div class="row mt-4">
                    <div class="col-md-6">
                        <a href="{% url 'proc_menu_alias' %}" class="btn btn-secondary btn-block">Voltar</a>
                    </div>
                    <div class="col-md-6 text-end">
                        <button type="submit" class="btn btn-primary btn-block">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

bdclinica/myapp/templates/myapp/procedimento_list.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}
{% load render_table from django_tables2 %}

{% block title %}Lista de Procedimentos{% endblock %}

{% block content %}
<div class="container">
    <div class="custom-card">
        <div class="custom-header">
            <h1>Lista de Procedimentos</h1>
        </div>
        <div class="custom-body">
            <div class="image-container">
                <img src="{% static 'procedimentos.png' %}" alt="Teste" width="200px">
            </div>
            <div class="table-responsive">
                {% render_table table %}
            </div>
        </div>
        <div class="custom-footer">
            <!-- Botões descomentados conforme necessidade -->
            <!-- <a href="{% url 'procedimento_create_alias' %}" class="btn btn-success">Adicionar Procedimento</a> -->
            <!-- <a href="{% url 'index_alias' %}" class="btn btn-secondary">Voltar ao Menu</a> -->
        </div>
    </div>
</div>
{% endblock %}

bdclinica/myapp/templates/myapp/user_delete.html
{% extends "base.html" %}

{% block title %}Excluir Usuario{% endblock %}

{% block content %}
<div class="container">
    <div class="card mt-5">
        <div class="card-header">
            <center>
            <h1>Tem certeza que deseja excluir este Usuario?</h1>
            </center>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <center>
                <div class="form-group">
                    <button type="submit" class="btn btn-danger">Excluir</button>
                    <a href="{% url 'user_menu_alias' %}" class="btn btn-secondary">Cancelar</a>
                </center>
                </div>
            </form> 
        </div>
    </div>
</div>
{% endblock %}

bdclinica/myapp/templates/myapp/user_form.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}

{% block title %}{% if form.instance.pk %}Editar Usuário{% else %}Criar Usuário{% endif %}{% endblock %}

{% block content %}
<div class="container">
    <div class="custom-card">
        <div class="custom-header text-center">
            <h1>{% if form.instance.pk %}Editar Usuário{% else %}Criar Usuário{% endif %}</h1>
        </div>
        <div class="custom-body text-center">
            <div class="image-container">
                <img src="{% static 'users.png' %}" class="img-fluid my-4" alt="Usuário" width="200px">
            </div>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.username placeholder='Usuário' %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 mb-3">
        
                    </div>
                    <div class="col-md-6 mb-3">
                   
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
               
                    </div>
                </div>

                <!-- Campo de seleção do tipo de usuário -->
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="id_tipo_usuario">Tipo de Usuário:</label>
                        <select name="tipo_usuario" id="id_tipo_usuario" class="form-control">
                            <option value="" selected>Selecione...</option>
                            <option value="paciente">Paciente</option>
                            <option value="medico">Médico</option>
                            <option value="funcionario">Funcionário</option>
                        </select>
                    </div>
                </div>

                <!-- Campos extras (exibidos dinamicamente) -->
                <div id="extra-fields"></div>

                <!-- Campo de senha para novo usuário -->
                {% if not form.instance.pk %}
                <div class="row">
                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.password1 placeholder='Senha' %}
                    </div>
                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.password2 placeholder='Confirme a Senha' %}
                    </div>
                </div>
                {% endif %}

                <div class="row mt-4">
                    <div class="col-md-6">
                        <a href="{% url 'user_menu_alias' %}" class="btn btn-secondary btn-block">Voltar</a>
                    </div>
                    <div class="col-md-6 text-end">
                        <button type="submit" class="btn btn-primary btn-block">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    document.getElementById("id_tipo_usuario").addEventListener("change", function() {
        let tipo = this.value;
        let extraFields = document.getElementById("extra-fields");
        extraFields.innerHTML = ""; // Limpa os campos extras

        if (tipo === "paciente") {
            extraFields.innerHTML = `
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="id_data_nascimento">Data de Nascimento:</label>
                        <input type="date" name="data_nascimento" id="id_data_nascimento" class="form-control">
                    </div>
                </div>
            `;
        } else if (tipo === "medico") {
            extraFields.innerHTML = `
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="id_crm">CRM:</label>
                        <input type="text" name="crm" id="id_crm" class="form-control">
                    </div>
                </div>
            `;
        } else if (tipo === "funcionario") {
            extraFields.innerHTML = `
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="id_cargo">Cargo:</label>
                        <input type="text" name="cargo" id="id_cargo" class="form-control">
                    </div>
                </div>
            `;
        }
    });
</script>

{% endblock %}

bdclinica/myapp/templates/myapp/user_form2.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}

{% block title %}{% if form.instance.pk %}Editar Usuário{% else %}Criar Usuário{% endif %}{% endblock %}

{% block content %}
<div class="container">
    <div class="custom-card">
        <div class="custom-header text-center">
            <h1>{% if form.instance.pk %}Editar Usuário{% else %}Criar Usuário{% endif %}</h1>
        </div>
        <div class="custom-body text-center">
            <div class="image-container">
                <img src="{% static 'users.png' %}" class="img-fluid my-4" alt="Usuário" width="200px">
            </div>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.username placeholder='Usuário' %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.first_name placeholder='Primeiro Nome' %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.last_name placeholder='Ultimo Nome' %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.email placeholder='Email' %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 mb-3">
        
                    </div>
                    <div class="col-md-6 mb-3">
                   
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 mb-3">
               
                    </div>
                </div>

                <div class="row mt-4">
                    <div class="col-md-6">
                        <a href="{% url 'user_menu_alias' %}" class="btn btn-secondary btn-block">Voltar</a>
                    </div>
                    <div class="col-md-6 text-end">
                        <button type="submit" class="btn btn-primary btn-block">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

bdclinica/myapp/templates/myapp/user_menu.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}
{% load render_table from django_tables2 %}

{% block title %}Gerenciar Usuários{% endblock %}

{% block content %}
<div class="container">
    <div class="custom-card">
        <Center>
        <div class="custom-header">
            <h1>Gerenciar Usuários</h1>
        </div>
        </Center>
        <div class="custom-body">
            <Center>
            <div class="image-container">
                <img src="{% static 'users.png' %}" alt="Menu" width="200px">
            </div>
            </Center> 
            <div class="table-responsive">
                {% render_table table %}
            </div>
            <div class="button-group">
                <a href="{% url 'user_create_alias' %}" class="btn btn-primary">
                    <i class="bi bi-person-plus"></i> Incluir Novo Usuário
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}